# Generated by Django 5.0.4 on 2025-01-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesapi', '0007_alter_contact_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.CharField(default='2025-01-06', max_length=150),
        ),
    ]
