<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-12-11 09:13
=======
# Generated by Django 5.0.4 on 2025-01-06 10:45
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('tc', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.CharField(default=datetime.date.today, max_length=150)),
                ('phoneNumber', models.CharField(default=False, max_length=2322)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_provider', models.CharField(default='email', max_length=255)),
                ('total_ads_posted', models.PositiveIntegerField(default=0)),
                ('active_devices', models.PositiveIntegerField(default=0)),
                ('token_key', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('token_expiration_time', models.DurationField(default=datetime.timedelta(seconds=1))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('posted_by', models.CharField(default='null', max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('percentage', models.CharField(default='', max_length=200)),
                ('date_of_birth', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('ads_id', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_base64', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('add_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2332)),
                ('task', models.CharField(max_length=2332)),
                ('task_date', models.CharField(default='null', max_length=255)),
                ('report_of_work', models.CharField(max_length=2332)),
                ('completion_status', models.CharField(choices=[('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default='25%', max_length=128)),
                ('documnet', models.FileField(null=True, upload_to='')),
                ('comment', models.CharField(max_length=2332)),
                ('document_base64', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(default='', max_length=2322)),
            ],
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=17)),
                ('email', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=20, null=True)),
                ('Introduction', models.CharField(blank=True, max_length=2000, null=True)),
                ('filename', models.FileField(blank=True, max_length=232222, null=True, upload_to='')),
<<<<<<< HEAD
                ('created_at', models.CharField(default='2024-12-11', max_length=150)),
=======
                ('created_at', models.CharField(default='2025-01-06', max_length=150)),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
            ],
        ),
        migrations.CreateModel(
            name='JobsRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=200)),
                ('no_of_openings', models.IntegerField(default=None, null=True)),
                ('title', models.CharField(blank=True, max_length=2322, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('job_responsiblity', models.CharField(max_length=200)),
                ('technical_skills', models.CharField(max_length=200)),
                ('Preferred_qualification', models.CharField(max_length=200, null=True)),
                ('education', models.CharField(max_length=200, null=True)),
<<<<<<< HEAD
                ('created_at', models.CharField(default='2024-12-11', max_length=150)),
=======
                ('created_at', models.CharField(default='2025-01-06', max_length=150)),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
            ],
        ),
        migrations.CreateModel(
            name='LoginProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_images/')),
                ('userid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('image_base64', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +919999999999. Up to 14 digits allowed.', regex='^\\+?1?\\d{9,10}$')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of otp_sent')),
                ('validated', models.BooleanField(default=False, help_text='If it is true, that means user have validate otp correctly in second API')),
                ('otp_session_id', models.CharField(default='', max_length=120, null=True)),
                ('username', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryDaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=121111, null=True)),
                ('teleId', models.IntegerField(default=None, null=True)),
<<<<<<< HEAD
                ('date', models.CharField(default='2024-12-11', max_length=10)),
=======
                ('date', models.CharField(default='2025-01-06', max_length=10)),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
            ],
        ),
        migrations.CreateModel(
            name='UserLoginTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_login_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
