<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-12-11 12:06
=======
# Generated by Django 5.0.4 on 2025-01-06 10:52
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='SpareParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Wheels & Tyres', 'Wheels & Tyres'), ('Audio & Other', 'Audio & Other'), ('Other Spare Parts', 'Other Spare Parts')], max_length=100)),
                ('ad_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Auto-rickshaws & E-rickshaws', 'Auto-rickshaws & E-rickshaws'), ('Buses', 'Buses'), ('Trucks', 'Trucks'), ('Pick-up vans', 'Pick-up vans'), ('Pick-up trucks', 'Pick-up trucks'), ('Heavy Machinery', 'Heavy Machinery'), ('Scrap Cars', 'Scrap Cars'), ('Others', 'Others')], max_length=100)),
                ('year', models.CharField(max_length=120)),
                ('km_driven', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ad_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
