<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-12-24 06:05
=======
# Generated by Django 5.0.4 on 2025-01-06 10:51
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingandGardening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Farm Equipment', 'Farm Equipment'), ('Plants & Seeds', 'Plants & Seeds'), ('Gardening Tools', 'Gardening Tools'), ('Livestock', 'Livestock'), ('Organic Produce', 'Organic Produce')], max_length=150)),
                ('images', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
