<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-12-16 08:46
=======
# Generated by Django 5.0.4 on 2025-01-06 10:52
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToysandGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Action Figures', 'Action Figures'), ('Educational Toys', 'Educational Toys'), ('Board Games', 'Board Games'), ('Puzzles', 'Puzzles')], max_length=100)),
<<<<<<< HEAD
=======
                ('images', models.ImageField(upload_to='images/')),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.IntegerField()),
                ('location', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
