# Generated by Django 5.0.4 on 2024-12-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToysandGames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toysandgames',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
