# Generated by Django 5.0.4 on 2024-12-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToysandGames', '0002_toysandgames_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toysandgames',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
