<<<<<<< HEAD
# Generated by Django 5.0.4 on 2025-01-02 10:04
=======
# Generated by Django 5.0.4 on 2025-01-06 10:50
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('age_group', models.CharField(choices=[('0-3', '0-3'), ('4-7', '4-7'), ('8-12', '8-12')], max_length=5)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='children_book/')),
                ('phone_number', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('picture_books', 'Picture Books'), ('chapter_books', 'Chapter Books'), ('educational_stories', 'Educational Stories'), ('activity_books', 'Activity Books')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
