<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-12-18 09:27
=======
# Generated by Django 5.0.4 on 2025-01-06 10:50
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceandTEch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=10)),
<<<<<<< HEAD
                ('photo', models.ImageField(null=True, upload_to='bookuploads/')),
=======
                ('photo', models.ImageField(null=True, upload_to='science&tech_uploads/')),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
                ('location', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('space', 'Space Exploration'), ('environment', 'Environmental Science'), ('robotics', 'Robotics')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
