# Generated by Django 5.0.4 on 2024-12-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science_technology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scienceandtech',
            name='photo',
            field=models.ImageField(null=True, upload_to='s_t_uploads/'),
        ),
    ]
