# Generated by Django 5.0.4 on 2025-01-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science_technology', '0002_alter_scienceandtech_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scienceandtech',
            name='photo',
            field=models.ImageField(null=True, upload_to='science&tech_uploads/'),
        ),
    ]
