<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-12-11 09:13
=======
# Generated by Django 5.0.4 on 2025-01-06 10:46
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d

import django.db.models.deletion
import django.utils.timezone
import embed_video.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('paymentapi', '__first__'),
=======
        ('paymentapi', '0001_initial'),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=2322)),
                ('password', models.CharField(max_length=2322)),
                ('name', models.CharField(max_length=2322, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tl_name', models.CharField(blank=True, max_length=255, null=True)),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.CharField(blank=True, max_length=255, null=True)),
                ('overdue_duedate', models.BooleanField(default=False)),
                ('task_done', models.BooleanField(default=False)),
                ('push_code', models.BooleanField(default=False)),
                ('dev_review', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFiled', models.CharField(max_length=1211)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLogin2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('login_time', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude1', models.CharField(blank=True, max_length=255, null=True)),
                ('lattiude1', models.CharField(blank=True, max_length=255, null=True)),
                ('logout_time', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude2', models.CharField(blank=True, max_length=255, null=True)),
                ('lattiude2', models.CharField(blank=True, max_length=255, null=True)),
                ('total_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateEnquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=232)),
                ('lastName', models.CharField(max_length=232)),
                ('email', models.CharField(max_length=343)),
                ('zip_code', models.CharField(max_length=232)),
<<<<<<< HEAD
                ('date_created', models.CharField(default='2024-12-11', max_length=150)),
=======
                ('date_created', models.CharField(default='2025-01-06', max_length=150)),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
            ],
        ),
        migrations.CreateModel(
            name='adsmangeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('connectMember', models.CharField(default='srishtisrija@gmail.com', max_length=223232)),
<<<<<<< HEAD
                ('date_created', models.CharField(default='2024-12-11', max_length=20)),
=======
                ('date_created', models.CharField(default='2025-01-06', max_length=20)),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
                ('adsUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_secondary_manual_roats', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_primary_manual_roats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(max_length=1211, null=True)),
                ('category', models.CharField(max_length=2322, null=True)),
                ('validity', models.CharField(max_length=2322, null=True)),
                ('city', models.CharField(max_length=2322, null=True)),
                ('visiblity', models.CharField(max_length=2322, null=True)),
                ('NoAds', models.CharField(max_length=2322, null=True)),
                ('teleSupport', models.BooleanField(default=True)),
                ('chatSupport', models.BooleanField(default=True)),
                ('dedicatedRm', models.BooleanField(default=True)),
                ('hol9Website', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('aadhar_card', models.FileField(upload_to='')),
                ('pan_card', models.FileField(upload_to='')),
                ('company_document', models.FileField(upload_to='')),
                ('company_document_type', models.TextField(default='null')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LastLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastloginValue', models.CharField(max_length=2322)),
                ('userlogin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=2322, null=True)),
                ('days', models.CharField(max_length=2322, null=True)),
                ('regulars', models.CharField(max_length=2322, null=True)),
                ('featured', models.CharField(max_length=2322, null=True)),
                ('response', models.CharField(max_length=1211, null=True)),
                ('teleSupport', models.BooleanField(default=False)),
                ('chatSupport', models.BooleanField(default=False)),
                ('dedicatedRm', models.BooleanField(default=False)),
                ('hol9Website', models.BooleanField(default=False)),
                ('OrderID', models.CharField(max_length=1211, null=True)),
<<<<<<< HEAD
                ('ads_timing', models.CharField(default='2024-12-11', max_length=30)),
=======
                ('ads_timing', models.CharField(default='2025-01-06', max_length=30)),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
                ('validity', models.CharField(max_length=2322, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetailsValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('date', models.CharField(default='2024-12-11', max_length=10)),
=======
                ('date', models.CharField(default='2025-01-06', max_length=10)),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
                ('OrderValue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentapi.order')),
                ('UserValue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('PlanValue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsapi.pricing')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=1502222222222222, null=True)),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('tags', models.CharField(max_length=150, null=True)),
                ('description', models.TextField()),
                ('seller_type', models.CharField(default='null', max_length=100)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair')], max_length=100)),
                ('state', models.CharField(default='null', max_length=50)),
                ('City', models.CharField(default='null', max_length=50)),
                ('locality', models.CharField(default='null', max_length=200)),
                ('zip_code', models.CharField(default='null', max_length=6)),
                ('lati', models.CharField(default=0, max_length=100)),
                ('long', models.CharField(default=0, max_length=100)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('subCategoryType', models.CharField(default='null', max_length=3232)),
                ('subCategoryValue', models.CharField(default='null', max_length=3232)),
                ('viewsproduct', models.IntegerField(default=0)),
                ('phoneNumber', models.CharField(blank=True, default='null', max_length=112, null=True)),
                ('BuildUpArea', models.CharField(blank=True, default='NoData', max_length=112111, null=True)),
                ('Flor', models.CharField(blank=True, default='NoData', max_length=112111, null=True)),
                ('ApartMentType', models.CharField(blank=True, default='NoData', max_length=112111, null=True)),
                ('Availability', models.CharField(blank=True, default='NoData', max_length=112111, null=True)),
                ('FurnishedType', models.CharField(blank=True, default='NoData', max_length=112111, null=True)),
                ('Property', models.CharField(blank=True, default='NoData', max_length=112111, null=True)),
                ('Parking', models.CharField(blank=True, default='NoData', max_length=112111, null=True)),
                ('PowerBackup', models.CharField(blank=True, default='NoData', max_length=112111, null=True)),
                ('Gym', models.CharField(blank=True, default='NoData', max_length=112111, null=True)),
                ('Garden', models.CharField(blank=True, default='NoData', max_length=112111, null=True)),
                ('Pool', models.CharField(blank=True, default='NoData', max_length=112111, null=True)),
                ('Lift', models.CharField(blank=True, default='NoData', max_length=112111, null=True)),
                ('PlanCategory', models.CharField(default='null', max_length=2322, null=True)),
                ('featured_ads', models.CharField(default='null', max_length=2322, null=True)),
                ('ads_limit', models.CharField(default='null', max_length=2322, null=True)),
                ('ads_timing', models.CharField(default='null', max_length=2322, null=True)),
                ('top_listing', models.CharField(default='null', max_length=2322, null=True)),
                ('support', models.CharField(default='null', max_length=2322, null=True)),
                ('colorCheck', models.CharField(default='null', max_length=2322, null=True)),
                ('sizeCheck', models.CharField(default='null', max_length=2322, null=True)),
                ('oldPetsCheck', models.CharField(default='null', max_length=2322, null=True)),
                ('start', models.CharField(default='null', max_length=2322, null=True)),
                ('end', models.CharField(default='null', max_length=2322, null=True)),
                ('school', models.CharField(default='null', max_length=2322, null=True)),
                ('college', models.CharField(default='null', max_length=2322, null=True)),
                ('brand', models.CharField(default='null', max_length=2322, null=True)),
                ('engine', models.CharField(default='null', max_length=2322, null=True)),
                ('year', models.CharField(default='null', max_length=2322, null=True)),
                ('kmdriven', models.CharField(default='null', max_length=2322, null=True)),
                ('setkmDriven', models.CharField(default='null', max_length=2322, null=True)),
                ('registrationYear', models.CharField(default='null', max_length=2322, null=True)),
                ('setregistrationYear', models.CharField(default='null', max_length=2322, null=True)),
                ('extraField', models.CharField(max_length=232333332, null=True)),
                ('adsType', models.CharField(default='null', max_length=232333332, null=True)),
                ('plan', models.CharField(default='null', max_length=232333332, null=True)),
                ('expiry', models.BooleanField()),
                ('deleted', models.BooleanField(default=False)),
                ('uuid', models.CharField(default='null', max_length=123123, null=True)),
                ('phoneNumberCollectVisiters', models.CharField(default='null', max_length=123123, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('validity', models.PositiveIntegerField(default=2)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAdsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=1502222222222222, null=True)),
                ('ads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsapi.product')),
            ],
        ),
        migrations.CreateModel(
            name='AdsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=23222)),
                ('datetimeValue', models.CharField(max_length=232)),
                ('message', models.CharField(max_length=23222)),
                ('rating', models.IntegerField(default=0)),
                ('ads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsapi.product')),
            ],
        ),
        migrations.CreateModel(
            name='AdsAdressLatLon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsapi.product')),
            ],
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, default='NoData', max_length=112111, null=True)),
                ('token', models.CharField(default='null', max_length=36)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsapi.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=23222)),
<<<<<<< HEAD
                ('dates', models.CharField(default='2024-12-11', max_length=30)),
=======
                ('dates', models.CharField(default='2025-01-06', max_length=30)),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
                ('ads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsapi.product')),
            ],
        ),
        migrations.CreateModel(
            name='Top50Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='adsapi.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserAdsVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsapi.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlistData', models.CharField(max_length=2322)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishListItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsapi.product')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
