<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-12-11 09:13
=======
# Generated by Django 5.0.4 on 2025-01-06 10:47
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/images')),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharastra', 'Maharastra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telengana', 'Telengana'), ('Tripura', 'Tripura'), ('Uttarkhand', 'Uttarkhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('West Bengal', 'West Bengal')], max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('author', models.CharField(default='null', max_length=150)),
                ('subtitle', models.CharField(default='null', max_length=150)),
                ('imagesecond', models.ImageField(default='null', upload_to='upload/images')),
<<<<<<< HEAD
                ('published_time', models.CharField(default='2024-12-11', max_length=150)),
=======
                ('published_time', models.CharField(default='2025-01-06', max_length=150)),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('video_base64', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=23222)),
                ('datetimeValue', models.CharField(max_length=232)),
                ('message', models.CharField(max_length=23222)),
<<<<<<< HEAD
                ('published_time', models.CharField(default='2024-12-11', max_length=232)),
=======
                ('published_time', models.CharField(default='2025-01-06', max_length=232)),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
                ('ads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogsapi.blogs')),
            ],
        ),
    ]
