<<<<<<< HEAD
# Generated by Django 5.0.4 on 2025-01-02 11:07
=======
# Generated by Django 5.0.4 on 2025-01-06 10:52
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographyEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Cameras', 'Cameras'), ('Lenses', 'Lenses'), ('Tripods', 'Tripods'), ('Accessories', 'Accessories')], max_length=150)),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photos', models.ImageField(upload_to='images/')),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
