<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-12-18 11:26
=======
# Generated by Django 5.0.4 on 2025-01-06 10:53
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthandBeauty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
<<<<<<< HEAD
                ('category', models.CharField(choices=[('Skincare', 'Skincare Products'), ('Haircare ', 'Haircare Products'), ('Makeup', 'Makeup & Cosmetics'), ('Personal Care ', 'Personal Care Appliances'), ('Fitness', 'Fitness Equipment'), ('Supplements', 'Supplements & Vitamins')], max_length=150)),
=======
                ('category', models.CharField(choices=[('Skincare', 'Skincare Products'), ('Haircare', 'Haircare Products'), ('Makeup', 'Makeup & Cosmetics'), ('Personal Care', 'Personal Care Appliances'), ('Fitness', 'Fitness Equipment'), ('Supplements', 'Supplements & Vitamins')], max_length=150)),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
                ('images', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
<<<<<<< HEAD
                ('phone_number', models.IntegerField()),
=======
                ('phone_number', models.CharField(max_length=15)),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
