# Generated by Django 5.0.4 on 2024-12-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthandbeauty', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthandBeauty',
        ),
    ]
