# Generated by Django 5.0.4 on 2024-12-18 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthandbeauty', '0002_delete_healthandbeauty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthandBeauty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Skincare', 'Skincare Products'), ('Haircare', 'Haircare Products'), ('Makeup', 'Makeup & Cosmetics'), ('Personal Care', 'Personal Care Appliances'), ('Fitness', 'Fitness Equipment'), ('Supplements', 'Supplements & Vitamins')], max_length=150)),
                ('images', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
