<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-12-11 09:14
=======
# Generated by Django 5.0.4 on 2025-01-06 10:47
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adsapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
<<<<<<< HEAD
                ('date', models.CharField(default='2024-12-11', max_length=10)),
=======
                ('date', models.CharField(default='2025-01-06', max_length=10)),
>>>>>>> 8a72e49cd22e840587db7c1423cb1ca18330101d
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='adsapi.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
