# Generated by Django 5.0.4 on 2025-01-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentbox', '0007_alter_adscomment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adscomment',
            name='date',
            field=models.CharField(default='2025-01-06', max_length=10),
        ),
    ]
