# Generated by Django 5.0.4 on 2024-12-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfitness',
            name='category',
            field=models.CharField(choices=[('supplements', 'Supplements'), ('  ', 'Workout Equipment'), ('health_monitors', 'Health Monitors'), ('yoga_mats', 'Yoga Mats')], max_length=50),
        ),
    ]
