# Generated by Django 5.0.4 on 2024-12-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='photos',
        ),
        migrations.AddField(
            model_name='foods',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='adfood/'),
        ),
    ]
