# Generated by Django 5.0.4 on 2024-12-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_foods_photos_foods_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='adDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='mobile',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='adTitle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='foods',
            name='category',
            field=models.CharField(choices=[('Foods', 'Foods'), ('Beverages', 'Beverages')], max_length=50),
        ),
        migrations.AlterField(
            model_name='foods',
            name='photo',
            field=models.ImageField(null=True, upload_to='fooduploads/'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
