# Generated by Django 5.0.4 on 2024-12-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0002_alter_profile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.CharField(default='2024-12-16', max_length=10),
        ),
    ]
